Recording and Viewing Availability
RIT-Crowd-Comic/Bot pull request #30
Opened 2024-06-05 00:12 UTC by nca6109

### Description
Added availability commands for members to record their own availability/unavailability, view their own recorded data, and view the availability of other server members

### /Commands
**/available set-availability**
Saves the times and days provided by the user to record when they are (typically) available during the week.
| Parameters | Description |
| --- | --- |
| time-from | Time that the user begins work for the day |
| time-to| Time the user stops work for the day|
| days (optional) | Days of the week that the user is active. If not provided, active days will be set as "daily" |

**/available set-unavailability**
Saves instances where the user will be unavailable (not-repeated).
| Parameters | Description |
| --- | --- |
| date-from | First day of unavailability |
| date-to| Final day of unavailability|
| time-from (optional) | Time on the first day that the user will be unavailable. Set to 12:00 am of that day if not entered. |
| time-to (optional) | Time on the final day that the user will no longer be unavailable. Set to 11:59 pm of that day if not entered. |
| reason (optional) | Reason for being unavailable |

**/available view-availability**
Sends the user a message with the requested availability.
| Parameters | Description |
| --- | --- |
| member (optional) | The server member to request the availability of. Requests for the sender if left empty |

**/available view-unavailability**
Sends the user a message that lists all of the days the requested server member is unavailable.
| Parameters | Description |
| --- | --- |
| member (optional) | The server member to request the availability of. Requests for the sender if left empty |

###Helper Methods (in `scr/utils/available.js`)
**createAvailability**
Returns an object that can be saved in the `available` property of the save data
| Parameters | Description |
| --- | --- |
| start (dayjs object) | Starting time for availability as an unformatted dayjs object |
| end (dayjs object) | Ending time for availability as an unformatted dayjs object |
| days (string) | Days of the week (or "daily") the user is available |

**createUnavailability**
Returns an object that can be pushed into the `unavailable` property array of the save data
| Parameters | Description |
| --- | --- |
| start (dayjs object) | Starting date and time of unavailability as an unformatted dayjs object |
| end (dayjs object) | Ending date and time of unavailability as an unformatted dayjs object |
| reason (string) | Reason for being out (can return an undefined reason property) |

**saveAvailability and saveUnavailability**
Saves the provided (un)availability to the storage file/database
| Parameters | Description |
| --- | --- |
| userId (string) | Id of the user whose data is being saved |
| userTag (string) | Tag of the user whose data is being saved |
| (un)availability (object) | Availability or unavailability object that is being saved to the file |
| path (string) | Path to the file to store the data in |

**newAvailabilityEntry** 
Creates a new object for a user in the stored data to add availability to
| Parameters | Description |
| --- | --- |
| userId (string) | Id of the user whose data is being saved |
| userTag (string) | Tag of the user whose data is being saved |

**loadAvailability**
Loads the data from the provided file path and returns the data as a JS object
| Parameters | Description |
| --- | --- |
| path (string) | Path to save date file |

###Save Data Schema Example
```
{
  "id": {
    "userId": "1223334444",
    "userTag": "servermember",
    "available": {
      "from": "2024-05-20T14:00:00.000Z",
      "to": "2024-08-09T22:00:00.000Z",
      "days": [
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday"
      ]
    },
    "unavailable": [
      {
        "from": "2024-07-03T05:00:00.000Z",
        "to": "2024-07-06T04:59:00.000Z",
        "reason": "Holiday"
      },
      {
        "from": "2024-08-01T20:00:00.000Z",
        "to": "2024-08-02T17:30:00.000Z"
      }
    ]
  }
}
```

2024-06-05 13:35 UTC, BlckHawker requested changes
- The following in printed in the catch of `01registerCommands.js`. I assume this is the reason why the `/available` commands do not show in Discord: 
   - "There was an error: SyntaxError: Missing catch or finally after try"
- Be sure to update the read me file with your commands
- We are trying to keep all functionality of command separate from the command code itself so Open AI can call the function without needing an instance of client or interaction. Look at #26 for more details. You can also look at `rememberMessages.js` as an example.

2024-06-05 13:35 UTC, BlckHawker commented on og_config.json
> +{
Can this file be deleted?

2024-06-05 13:35 UTC, BlckHawker commented on src/commands/availability/availability.js
> +    },
options can be removed

2024-06-05 13:35 UTC, BlckHawker commented on src/commands/availability/availability.js
> +// }
This is good for testing purposes, but can be removed now since the json should have this data structure

2024-06-05 13:35 UTC, BlckHawker commented on src/commands/availability/availability.js
> +
delete

2024-06-05 13:35 UTC, BlckHawker commented on src/commands/availability/availability.js
> +    if (userId === undefined || userTag === undefined) {
This check doesn't seem neccessary. If a user is required, the parameters should make it required. Otherwise, don't run the command

2024-06-05 13:35 UTC, BlckHawker commented on src/commands/availability/availability.js
> +        if (!dayjs(startAvail).isValid && !dayjs(endAvail).isValid)
This error checking should be in a separate method like createAvailability. The only purpose of a command is to call a method

2024-06-05 13:35 UTC, BlckHawker commented on src/commands/availability/availability.js
> +    if (userId === undefined || userTag === undefined) {
Error checking not needed

2024-06-05 13:35 UTC, BlckHawker commented on src/commands/availability/availability.js
> +    if (userId === undefined || userTag === undefined) {
Error checking not needed

2024-06-06 14:03 UTC, BlckHawker requested changes
Minor tweaks:

Subcommand is **availability** but read me states it's **available**

Fool proofing test:
- **set-unavailability**: same day is valid if no times are given, but given valid times is not allowed
![image](https://github.com/RIT-Crowd-Comic/Bot/assets/62062830/b342bc9a-f9ea-4fc8-aefe-b9e84bb0e6fc)
![image](https://github.com/RIT-Crowd-Comic/Bot/assets/62062830/4061e029-bb98-4a4b-bfd4-95791e7ae359)
- **view-availability** View my own availability without the member parameter works fine, but putting my own self as a member states there is no availability for this person
![image](https://github.com/RIT-Crowd-Comic/Bot/assets/62062830/b036c999-1f52-4175-ae77-18a913860c65)
![image](https://github.com/RIT-Crowd-Comic/Bot/assets/62062830/7b2e7ada-8089-4b7d-b1a6-35d0066e8c39)

- **view-unavailability** same issues with view-availability

2024-06-06 14:57 UTC, wct9667 commented
We can discuss another similar function to `setUnavail` for the openai, as I have it give 2 dates with times included already in this format "2024-05-20T14:00:00.000Z". Which would reduce the need for additional formatting and extra parameters.   
Ex. I tell the bot I am busy tomorrow from 10-11 and it outputs `from 2024-06-05T10:00:00Z to 2024-06-05T11:00:00Z for Busy`. 

I can make a helper function based on yours, I don't think you should have to change anything. 

Otherwise, same comments as the other review. Few small errors with how things are presented, otherwise it looks good.

I am also concerned about the `days` piece of availability for openai. But that is a later issue for now.

2024-06-06 15:40 UTC, BlckHawker approved these changes
![sonic-boom-knuckles](https://github.com/RIT-Crowd-Comic/Bot/assets/62062830/64a3c4f9-0851-4383-a514-f95f1882c756)

2024-06-06 15:43 UTC, merged